version: '2'
services:
  nginx:
    build:
      context: ./
      dockerfile: config/nginx/nginx.docker
    volumes:
      - ./wordpress:/var/www/
      - ./logs/nginx:/var/log/nginx:cached
    ports:
      - "8000:80"
    links:
      - phpfpm
  phpfpm:
    build:
      context: ./
      dockerfile: config/php-fpm/php-fpm.docker
    volumes:
      - ./wordpress:/var/www/
    depends_on:
      - mysql
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=mysql"
  mysql:
    image: mysql:5.7
    volumes:
      - "./storage/docker/mysql:/var/lib/mysql:delegated"
    ports:
      - "33061:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: password
